services:
  blazorpdf:
    build:
      context: .
      dockerfile: ./Gotho.BlazorPdf.Docs/Dockerfile
    container_name: blazorpdf
    ports:
      - 8080:8080
      - 8081:8081
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    restart: unless-stopped
